# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'GoogleMaps', '7.2.0'
   pod 'GooglePlaces', '7.2.0'
  # Pods for weatherApp

end
